version: 1

models:
  - name: clean_orders
    description: "This model processes the orders data by removing the prefix 'B-' from ORDER_ID and creating a new column ORDER_ID2."
    columns:
      - name: ORDER_ID
        description: "Original order ID with possible prefix 'B-'."
        tests:
          - not_null
          - unique
      
      - name: AMOUNT
        description: "Amount of the order."
        tests:
          - not_null

      - name: PROFIT
        description: "Profit from the order."
        tests:
          - not_null

      - name: QUANTITY
        description: "Quantity of items in the order."
        tests:
          - not_null

      - name: CATEGORY
        description: "Category of the product."
        tests:
          - not_null

      - name: SUBCATEGORY
        description: "Subcategory of the product."
        tests:
          - not_null

      - name: ORDER_ID2
        description: "Order ID without the 'B-' prefix."
        tests:
          - not_null
